### ISSUE TITLE
Create CORE rule editor template for USDM v3.0

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#390]

**Comment by ASL-rmarshall** [comment]
Proposal in which:
- Comments/questions are embedded as comments to show where they apply.  The comments/questions are also shown in a separate comment below.
- \<references in angle brackets\> refer to column headers in [USDM_CORE_Rules_for_Implementation.xlsx](https://cdisc.sharepoint.com/:x:/r/sites/ddf/Shared%20Documents/DDF3a/RuleDevelopment/[USDM_CORE_Rules_for_Implementation.xlsx](https://cdisc.sharepoint.com/:x:/r/sites/ddf/Shared%20Documents/DDF3a/RuleDevelopment/USDM_CORE_Rules_for_Implementation.xlsx?d=w9397fd1433aa44598982c380ef8fc3da&csf=1&web=1&e=qReade)?d=w9397fd1433aa44598982c380ef8fc3da&csf=1&web=1&e=qReade) (for now - these may be moved to RuleRequirements_v4)

Should this be stored somewhere? It could be stored as a yaml file in SharePoint or GitHub, or it could be created as a template USDM rule in the Rules Editor.

```yaml
Authorities:
  - Organization: CDISC
    Standards:
      - Name: USDM
        References:
          - Citations:
              # Would we want to include IG text (as a separate Citation) if available?
              - Cited Guidance: '<Textual statement of rule>'
                Document: 'USDM_CORE_Rules.xlsx'
                # Not sure if Item or Section are needed        
                Item: ''
                Section: ''
            Criteria:
              # Remove Logical Expression or populate with FHIR-like expressions?
              Logical Expression:
                Condition: ''
                Rule: ''
              Plain Language Expression: '<Plain Language Expression>'
              Type: Success
            Origin: USDM Conformance Rules
            # Remove Related Rules or do we want to record dependencies?
            Related Rules:
              - Id: ''
                Relationship: Predecessor | Related | Successor
            # Remove Release Notes?
            Release Notes: ''
            Rule Identifier:
              Id: '<Assigned CORE Rule ID>'
              Version: '1'
            # Remove Validator Rule Message?
            Validator Rule Message: ''
            Version: '1.0'
        Version: '3.0' | '4.0'
Check:
  all:
    - operator: variable_metadata_not_equal_to
    - ...: ''
  any:
    - operator: variable_metadata_not_equal_to
    - ...: ''
  not:
    operator: variable_metadata_not_equal_to
Core:
  Id: ''
  Status: Draft
Description: '<Description>'
# Use Executability to define ERROR (Fully Executable) vs WARNING (Partially Executable (i.e. needs further human review))?
Executability: >-
  Fully Executable | Not Executable | Partially Executable | Partially
  Executable - Possible Overreporting | Partially Executable - Possible
  Underreporting
# Match Datasets is optional (Is Relationship and Wildcard removed as not relevant for USDM)
Match Datasets:
  - Name: >-
      ...
    Keys:
      - ''
      - Left: ''
        Right: ''
# Operations is optional
Operations:
  - ...: ''
Outcome:
  Message: '<Error Message>'
  Output Variables:
    - variable_value_length
# May need an additional Rule Type for schema-based validation
Rule Type: Record Data
Scope:
  Entities:
    Exclude:
      - ''
    Include:
      - ''
Sensitivity: Record

```

**Comment by ASL-rmarshall** [comment]
Questions:
- Would we want to include IG text (as a separate `Citation` entry) if available?
- Not sure if `Item` or `Section` are needed: if so how should they be populated?
- Remove `Logical Expression` or populate with FHIR-like expressions?
- Remove `Related Rules` or do we want to record dependencies?
- Remove `Release Notes`? (I think this might be expected for new versions of any rule according to the CORE process)
- Remove `Validator Rule Message`?
- Use `Executability` to define ERROR (Fully Executable) vs WARNING (Partially Executable (i.e. needs further human review))?

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD 
As discussed, the information from the USDM_Core_Rules_for_Implementation.xlsx file has now been merged into the RuleRequirements_v4 spreadsheet - yellow columns have been added to the Overview sheet and I have copied the Questions sheet over.  I have removed the USDM_Core_Rules_for_Implementation.xlsx file from SharePoint to prevent confusion.

We decided that there should only be one plain text description of the check, so please review any text I've added in either of the "Suggested Updated Textual Statement of Rule" and "Plain Language Expression" columns (columns E and F). If you agree either is preferable to the existing "Textual statement of rule", please move the preferred text across to column D and clear columns E and F.  If neither is preferable, please leave the suggested update(s) in place and we can discuss and resolve later by either applying the change or deleting the suggestion. (Once all the current suggestions in the "Plain Text Expression" column have been either applied or deleted, we will delete this column and use only the "Suggested Updated Textual Statement of Rule" column for further amendment suggestions).

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD I have created the following as "USDM_TEMPLATE" in the Rule Editor. Note that I had to create separate sections for v3.0 and v4.0 because the error reported by the rule editor for `'3.0' | '4.0'` was preventing the template saving properly.
```yaml
Authorities:
  - Organization: CDISC
    Standards:
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: '<Textual statement of rule>'
                Document: 'USDM_CORE_Rules.xlsx'
            Origin: 'USDM Conformance Rules'
            Rule Identifier:
              Id: 'USDM_TEMPLATE'
              Version: '1'
            Version: '1.0'
        Version: '3.0'
      - Name: USDM
        References:
          - Citations:
              - Cited Guidance: '<Textual statement of rule>'
                Document: 'USDM_CORE_Rules.xlsx'
            Origin: 'USDM Conformance Rules'
            Rule Identifier:
              Id: 'USDM_TEMPLATE'
              Version: '1'
            Version: '1.0'
        Version: '4.0'
Check:
  all:
    - operator: variable_metadata_not_equal_to
    - ...: ''
  any:
    - operator: variable_metadata_not_equal_to
    - ...: ''
  not:
    operator: variable_metadata_not_equal_to
Core:
  Id: ''
  Status: Draft
  Version: '1'
Description: '<Description>'
Executability: >-
  Fully Executable | Not Executable | Partially Executable | Partially
  Executable - Possible Overreporting | Partially Executable - Possible
  Underreporting
# Match Datasets is optional
# - if needed, remove this comment
# - if not needed, remove the Match Datasets section
Match Datasets:
  - Keys:
      - ''
      - Left: ''
        Right: ''
    Name: >-
      ...
# Operations is optional
# - if needed, remove this comment
# - if not needed, remove the Operations section
Operations:
  - ...: ''
Outcome:
  Message: '<Error Message>'
  Output Variables:
    - parent_entity
    - parent_id
    - parent_rel
    - id
    - name
Rule Type: Record Data
Scope:
  Entities:
    Exclude:
      - ''
    Include:
      - ''
Sensitivity: Record
```
